### PR TITLE
fix(valid): should throw if modifier is not valid

### LINKED ISSUE #59: should throw if modifier is not valid
**Actual**

```js
new BemEntityName({
    block: 'button',
    mod: { val: 'action' }
});

// ➜ BemEntityName { block: 'button' }

new BemEntityName({
    block: 'button',
    mod: {}
});

// ➜ BemEntityName { block: 'button' }
```

**Expected**

```js
new BemEntityName({
    block: 'button',
    mod: { val: 'action' }
});

// ➜ This is not valid BEM entity: the field `mod.name` is undefined.

new BemEntityName({
    block: 'button',
    mod: {}
});

// ➜ This is not valid BEM entity: the field `mod.name` is undefined.
```

### PR DESCRIPTION
**Pull request by blond**
Resolved #59

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -32,19 +32,20 @@ module.exports = class BemEntityName {
...
+        const modName = (typeof modObj === 'string' ? modObj : modObj && modObj.name) || obj.modName;
+        const hasModVal = modObj && modObj.hasOwnProperty('val') || obj.hasOwnProperty('modVal');
 
+        if (modName) {
             data.mod = {
                 name: modName,
-                val: modVal
+                val: hasModVal ? modObj && modObj.val || obj.modVal : true
             };
+        } else if (modObj || hasModVal) {
```
Comment (skad0) [inline index.js]: hasModVal already checks for modObj
